<?php

return [
    /*
    |--------------------------------------------------------------------------
    | App Frontend URL
    |--------------------------------------------------------------------------
    |
    | This value is used as applications entry point, except for the api routes, 
    | also for email links to the front end
    |
    */

    'app_frontend_url' => env('APP_FRONTEND_URL') ?? env('APP_URL'),

    /*
    |--------------------------------------------------------------------------
    | Main Administrator Email
    |--------------------------------------------------------------------------
    |
    | This value is used to send all automatic emails generated by the application
    |
    */

    'main_admin_email' => env('MAIN_ADMIN_EMAIL', null),

];
